### PR TITLE
Added new file

### PR DESCRIPTION
**Pull request by CarlosSardo**

### CODE REVIEW

**Comment by CarlosSardo** [comment]
Challenge 01 done @krist00fer . Can you please review, accept & merge this PR? Thanks!

**Comment by krist00fer** [comment]
Seems to be a merge conflict

**Comment by CarlosSardo** [comment]
@krist00fer conflict is solved. Thanks!

**Comment by krist00fer** [comment]
Thanks for helping out with the merge conflicts

**Pull request merged**
